// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TLqIDZjJIg7sUsO4YBIq8Km5VKRILVk',
    appId: '1:639915030503:web:32a2a031d7f8e237e3af42',
    messagingSenderId: '639915030503',
    projectId: 'match-web-90f3f',
    authDomain: 'match-web-90f3f.firebaseapp.com',
    storageBucket: 'match-web-90f3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUHokOf5TJGNMavDGyp6HI4k95x0GTxs',
    appId: '1:639915030503:android:3157cd8a718061e6e3af42',
    messagingSenderId: '639915030503',
    projectId: 'match-web-90f3f',
    storageBucket: 'match-web-90f3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqUZZkyekI_7mtgIYEO48GFLY2nCPm3YQ',
    appId: '1:639915030503:ios:c090b621c33eeb2de3af42',
    messagingSenderId: '639915030503',
    projectId: 'match-web-90f3f',
    storageBucket: 'match-web-90f3f.firebasestorage.app',
    iosBundleId: 'com.example.matchWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1TLqIDZjJIg7sUsO4YBIq8Km5VKRILVk',
    appId: '1:639915030503:web:41779bfc74b0febce3af42',
    messagingSenderId: '639915030503',
    projectId: 'match-web-90f3f',
    authDomain: 'match-web-90f3f.firebaseapp.com',
    storageBucket: 'match-web-90f3f.firebasestorage.app',
  );
}
